# Generated by Django 3.1.1 on 2022-01-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=6)),
                ('subreddit', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('score', models.IntegerField()),
                ('total_comments', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
