# Generated by Django 3.2.2 on 2022-01-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('permalink', models.URLField(null=True)),
                ('score', models.IntegerField()),
                ('comments', models.IntegerField(null=True)),
                ('created', models.DateTimeField()),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('nsfw', models.BooleanField(null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('subscribers', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subreddits.subreddit')),
            ],
        ),
    ]
