# Generated by Django 3.2.2 on 2022-01-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0002_alter_post_subreddit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['user', 'post_id', 'score']},
        ),
        migrations.AlterModelOptions(
            name='subreddit',
            options={'ordering': ['subreddit']},
        ),
    ]
