# Generated by Django 3.2.2 on 2022-01-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0003_auto_20220123_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreddits', to='subreddits.subreddit'),
        ),
    ]
